services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chat_backend
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - redis
            - mongodb
        environment:
            - PORT=3000
            - JWT_SECRET=secret
            - JWT_EXPIRES_IN=7d
            - MONGO_URI=mongodb://mongodb:27017/chatapp
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - chat-network

    redis:
        image: redis:8-alpine
        container_name: chat_redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - chat-network

    mongodb:
        image: mongo:latest
        container_name: chat_mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=chatapp
        networks:
            - chat-network

networks:
    chat-network:
        driver: bridge

volumes:
    mongodb_data:
