services:
    backend:
        build: .
        container_name: chat_backend
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - redis
        volumes:
            - .:/app
    redis:
        image: redis:8-alpine
        container_name: chat_redis
        restart: always
        ports:
            - "6379:6379"
